<?php
	//The mysqli extension allows you to access the functionality provided by MySQL 4.1 and above
	$con = @mysqli_connect("127.0.0.1","root","","crime_data_mining");//@ is error control operator 
	//When prepended to an expression in PHP, any error messages that might be generated by that expression will be ignored.
	if (mysqli_connect_errno()){
		die("Failed to connect to MySQL: " . mysqli_connect_error());
	}
?>
